version: '3'

services:
  api:
    build: express/
    depends_on:
      - 'database'
    ports: 
      - '3001:3001'
    volumes:
      - ./express:/api

  react:
    build: react/
    environment: 
      CHOKIDAR_USEPOLLING: 'true'
    depends_on:
      - 'database'
    ports:
      - '3000:3000'
    volumes:
      - ./react/public:/app/public
      - ./react/src:/app/src

  database:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=payment_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql